id: 9d9785a0146f4acda5119979ba3644ff
initial_creation_type: ocr
source_metadata:
  volumes:
    f06087df557e48f6a18d3140dfddcdf7:
      base_file: v063.txt
      image_group_id: I1PD95909
      title: ''
      total_pages: 1902
      volume_number: 64
